"""Build deterministic Docker Compose text from one validated config document."""

import json
import re

from labpulse.common.config import ConfigDocument
from labpulse.hardware.registry import get_driver_spec


def service_slug(service_name: str) -> str:
    """Convert one service key into a Docker/Compose-friendly slug."""

    normalized = re.sub(r"[^a-zA-Z0-9]+", "-", service_name).strip("-").lower()
    return normalized or "service"


def _hardware_command(service_name: str) -> str:
    """Serialize one explicit hardware command as Compose list syntax."""

    return json.dumps(
        [
            "python",
            "-m",
            "labpulse.hardware",
            "--config",
            "/app/config.yaml",
            "--service",
            service_name,
        ]
    )


def _sms_command() -> str:
    """Serialize the SMS service command as Compose list syntax."""

    return json.dumps(
        ["python", "-m", "labpulse.sms", "--config", "/app/config.yaml"]
    )


def build_compose(
    document: ConfigDocument,
    *,
    config_mount_source: str,
    runtime_image: str,
    force_simulated: bool = False,
) -> str:
    """Return complete deterministic Compose text without writing files."""

    if not runtime_image.strip():
        raise ValueError("runtime image cannot be empty")
    if not config_mount_source.strip():
        raise ValueError("config mount source cannot be empty")
    config = document.config
    enabled_services = [
        (service_name, service)
        for service_name, service in config.services.items()
        if service.enabled
    ]
    if not enabled_services:
        raise ValueError("configuration has no enabled hardware services")

    lines = [
        "# Generated by generate_compose.sh",
        "# Edit ./config.yaml in this Compose folder, then regenerate this file.",
        "# Do not edit this file by hand.",
        "",
        "x-labpulse-runtime-base: &labpulse-runtime-base",
        f"  image: {runtime_image}",
        "  depends_on:",
        "    - mosquitto",
        "  environment:",
        "    MQTT_BROKER: mosquitto",
        "    MQTT_PORT: 1883",
        "    LABPULSE_LOG_DIR: /app/logs",
        "  restart: unless-stopped",
        "",
        "services:",
        "  homeassistant:",
        "    container_name: labpulse-homeassistant",
        "    image: ghcr.io/home-assistant/home-assistant:stable",
        "    volumes:",
        "      - ./homeassistant/config:/config",
        "      - /etc/localtime:/etc/localtime:ro",
        "      - /run/dbus:/run/dbus:ro",
        "    restart: unless-stopped",
        "    privileged: true",
        "    network_mode: host",
        "    environment:",
        "      TZ: Europe/London",
        "",
        "  mosquitto:",
        "    container_name: labpulse-mqtt",
        "    image: eclipse-mosquitto:2",
        "    ports:",
        '      - "127.0.0.1:1883:1883"',
        "    volumes:",
        "      - ./mosquitto/config:/mosquitto/config",
        "      - ./mosquitto/data:/mosquitto/data",
        "      - ./mosquitto/log:/mosquitto/log",
        "      - /etc/localtime:/etc/localtime:ro",
        "    restart: unless-stopped",
        "",
        "  labpulse-sms:",
    ]

    if config.sms.dry_run:
        lines.extend(
            [
                "    <<: *labpulse-runtime-base",
                "    volumes:",
                "      - ./logs:/app/logs",
                f"      - {config_mount_source}:/app/config.yaml:ro",
                "      - /etc/localtime:/etc/localtime:ro",
            ]
        )
    else:
        lines.extend(
            [
                f"    image: {runtime_image}",
                "    depends_on:",
                "      - mosquitto",
                "    volumes:",
                "      - ./logs:/app/logs",
                f"      - {config_mount_source}:/app/config.yaml:ro",
                "      - /etc/localtime:/etc/localtime:ro",
                "      - /run/dbus:/run/dbus:ro",
                "      - /dev:/dev",
                "    privileged: true",
                "    environment:",
                "      MQTT_BROKER: mosquitto",
                "      MQTT_PORT: 1883",
                "      LABPULSE_LOG_DIR: /app/logs",
                "    restart: unless-stopped",
            ]
        )
    lines.extend(
        [
            "    container_name: labpulse-sms",
            f"    command: {_sms_command()}",
            "",
        ]
    )

    used_container_names: set[str] = set()
    for service_name, service in enabled_services:
        slug = service_slug(service_name)
        container_name = f"labpulse-{slug}"
        if container_name in used_container_names:
            raise ValueError(
                f"service name {service_name!r} creates duplicate container "
                f"name {container_name!r}"
            )
        used_container_names.add(container_name)

        definition = get_driver_spec(service.driver.type)
        requirements = definition.resolve_resources(
            service.driver.options,
            force_simulated,
        )
        service_lines = [
            f"  {container_name}:",
            "    <<: *labpulse-runtime-base",
            "    volumes:",
            "      - ./logs:/app/logs",
            f"      - {config_mount_source}:/app/config.yaml:ro",
            "      - /etc/localtime:/etc/localtime:ro",
        ]
        if requirements.devices:
            service_lines.append("    devices:")
            service_lines.extend(
                f"      - {device}:{device}" for device in requirements.devices
            )
        service_lines.extend(f"      - {mount}" for mount in requirements.mounts)
        if requirements.privileged:
            service_lines.append("    privileged: true")
        service_lines.extend(
            [
                f"    container_name: {container_name}",
                f"    command: {_hardware_command(service_name)}",
                "",
            ]
        )
        lines.extend(service_lines)
    return "\n".join(lines)
