"""Build deterministic Docker Compose text from one validated config document."""

import json
import re

from labpulse.common.config import ConfigDocument
from labpulse.hardware.registry import get_driver_definition


def service_slug(service_name: str) -> str:
    """Convert one service key into a Docker/Compose-friendly slug."""

    normalized = re.sub(r"[^a-zA-Z0-9]+", "-", service_name).strip("-").lower()
    return normalized or "service"


def build_compose(
    document: ConfigDocument,
    *,
    config_mount_source: str,
    runtime_image: str,
    force_simulated: bool = False,
) -> str:
    """Return complete deterministic Compose text without writing files."""

    if not runtime_image.strip():
        raise ValueError("runtime image cannot be empty")
    if not config_mount_source.strip():
        raise ValueError("config mount source cannot be empty")
    config = document.config
    enabled_services = [(name, service) for name, service in config.services.items() if service.enabled]
    # Fake-USB mode never starts physical actuator workers. Regeneration uses
    # --remove-orphans, so changing into fake mode also stops any old output
    # container and lets its orderly shutdown apply the configured safe state.
    enabled_outputs = (
        []
        if force_simulated
        else [(name, output) for name, output in config.outputs.items() if output.enabled]
    )
    if not enabled_services:
        raise ValueError("configuration has no enabled hardware services")

    # Start with the shared Docker settings and the three fixed services. The
    # YAML anchor lets every LabPulse worker inherit the same image, MQTT
    # address, logging path, and restart policy.
    lines = [
        "# Generated by generate_compose.sh",
        "# Edit ./config.yaml in this Compose folder, then regenerate this file.",
        "# Do not edit this file by hand.",
        "",
        "x-labpulse-runtime-base: &labpulse-runtime-base",
        f"  image: {runtime_image}",
        "  depends_on:",
        "    - mosquitto",
        "  environment:",
        "    MQTT_BROKER: mosquitto",
        "    MQTT_PORT: 1883",
        "    LABPULSE_LOG_DIR: /app/logs",
        "  restart: unless-stopped",
        "",
        "services:",
        "  homeassistant:",
        "    container_name: labpulse-homeassistant",
        "    image: ghcr.io/home-assistant/home-assistant:stable",
        "    volumes:",
        "      - ./homeassistant/config:/config",
        "      - /etc/localtime:/etc/localtime:ro",
        "      - /run/dbus:/run/dbus:ro",
        "    restart: unless-stopped",
        "    privileged: true",
        "    network_mode: host",
        "    environment:",
        "      TZ: Europe/London",
        "",
        "  mosquitto:",
        "    container_name: labpulse-mqtt",
        "    image: eclipse-mosquitto:2",
        "    ports:",
        '      - "127.0.0.1:1883:1883"',
        "    volumes:",
        "      - ./mosquitto/config:/mosquitto/config",
        "      - ./mosquitto/data:/mosquitto/data",
        "      - ./mosquitto/log:/mosquitto/log",
        "      - /etc/localtime:/etc/localtime:ro",
        "    restart: unless-stopped",
        "",
        "  labpulse-sms:",
    ]

    lines.extend([
        "    <<: *labpulse-runtime-base",
        "    volumes:",
        "      - ./logs:/app/logs",
        f"      - {config_mount_source}:/app/config.yaml:ro",
        "      - /etc/localtime:/etc/localtime:ro",
    ])
    # Dry-run SMS never touches the host modem. Real delivery needs DBus and
    # device access so mmcli can communicate with ModemManager.
    if not config.sms.dry_run:
        lines.extend(["      - /run/dbus:/run/dbus:ro", "      - /dev:/dev", "    privileged: true"])
    sms_command = json.dumps(["python", "-m", "labpulse.sms", "--config", "/app/config.yaml"])
    lines.extend(
        [
            "    container_name: labpulse-sms",
            f"    command: {sms_command}",
            "",
        ]
    )

    used_container_names: set[str] = set()
    # Each enabled hardware service becomes one independently restartable
    # container with only the host access requested by its selected driver.
    for service_name, service in enabled_services:
        slug = service_slug(service_name)
        container_name = f"labpulse-{slug}"
        if container_name in used_container_names:
            raise ValueError(
                f"service name {service_name!r} creates duplicate container "
                f"name {container_name!r}"
            )
        used_container_names.add(container_name)

        definition = get_driver_definition(service.driver.type)
        requirements = definition.container_requirements(service.driver.options, force_simulated)
        service_lines = [
            f"  {container_name}:",
            "    <<: *labpulse-runtime-base",
            "    volumes:",
            "      - ./logs:/app/logs",
            f"      - {config_mount_source}:/app/config.yaml:ro",
            "      - /etc/localtime:/etc/localtime:ro",
        ]
        if requirements.devices:
            service_lines.append("    devices:")
            service_lines.extend(
                f"      - {device}:{device}" for device in requirements.devices
            )
        service_lines.extend(f"      - {mount}" for mount in requirements.mounts)
        if requirements.privileged:
            service_lines.append("    privileged: true")
        # JSON list syntax is also valid YAML and safely quotes service names in
        # the generated Compose command.
        command = json.dumps([
            "python", "-m", "labpulse.hardware", "--config", "/app/config.yaml", "--service", service_name
        ])
        service_lines.extend([f"    container_name: {container_name}", f"    command: {command}", ""])
        lines.extend(service_lines)

    # Outputs use their own MQTT subscriber process because commands and
    # fail-safe timing have a different lifecycle from polled measurements.
    for output_name, output in enabled_outputs:
        slug = service_slug(output_name)
        container_name = f"labpulse-output-{slug}"
        definition = get_driver_definition(output.driver.type)
        requirements = definition.container_requirements(output.driver.options, force_simulated)
        output_lines = [
            f"  {container_name}:",
            "    <<: *labpulse-runtime-base",
            "    volumes:",
            "      - ./logs:/app/logs",
            f"      - {config_mount_source}:/app/config.yaml:ro",
            "      - /etc/localtime:/etc/localtime:ro",
        ]
        if requirements.devices:
            output_lines.append("    devices:")
            output_lines.extend(
                f"      - {device}:{device}" for device in requirements.devices
            )
        output_lines.extend(f"      - {mount}" for mount in requirements.mounts)
        if requirements.privileged:
            output_lines.append("    privileged: true")
        command = json.dumps([
            "python", "-m", "labpulse.output", "--config", "/app/config.yaml", "--output", output_name
        ])
        output_lines.extend([f"    container_name: {container_name}", f"    command: {command}", ""])
        lines.extend(output_lines)
    return "\n".join(lines)
