"""Generate the Mosquitto configuration owned by LabPulse deployment."""

from pathlib import Path

from labpulse.common.config import ConfigDocument


EXTERNAL_MQTT_FILES = (
    "certs/server.crt",
    "certs/server.key",
    "external-passwords",
    "external-acl",
)


def build_mosquitto_config(document: ConfigDocument) -> str:
    """Return listener configuration for internal and optional external MQTT."""

    external = document.config.mqtt.external_listener
    lines = [
        "# Generated by LabPulse. Edit ~/labpulse-live/config.yaml, not this file.",
        "per_listener_settings true",
        "persistence true",
        "persistence_location /mosquitto/data/",
        "log_dest stdout",
        "",
        "listener 1883",
        "allow_anonymous true",
    ]
    if external.enabled:
        lines.extend(
            [
                "",
                "# Authenticated TLS endpoint for control-PC measurement publishers.",
                "listener 8883",
                "allow_anonymous false",
                "password_file /mosquitto/config/external-passwords",
                "acl_file /mosquitto/config/external-acl",
                "certfile /mosquitto/config/certs/server.crt",
                "keyfile /mosquitto/config/certs/server.key",
                "require_certificate false",
                "tls_version tlsv1.2",
            ]
        )
    return "\n".join(lines) + "\n"


def validate_external_mqtt_files(document: ConfigDocument, project_dir: Path) -> None:
    """Fail before deployment when an enabled TLS listener lacks credentials."""

    if not document.config.mqtt.external_listener.enabled:
        return
    config_dir = project_dir / "mosquitto" / "config"
    missing = [name for name in EXTERNAL_MQTT_FILES if not (config_dir / name).is_file()]
    if missing:
        formatted = ", ".join(str(config_dir / name) for name in missing)
        raise ValueError(
            "mqtt.external_listener is enabled but required TLS/authentication "
            f"files are missing: {formatted}"
        )
