"""Assemble and write the supported LabPulse Lovelace YAML dashboard.

Page-specific cards live in :mod:`labpulse.homeassistant.dashboard`. This
module is the composition and filesystem boundary: it fixes view order,
serializes the resulting plain data, and never accesses Home Assistant's
private ``.storage`` directory.
"""

from __future__ import annotations

import yaml

from labpulse.common.config import LabPulseConfig

from .dashboard.alarm_setup import (
    ALARM_SETUP_PATH,
    alarm_setup_landing_sections,
    power_alarm_subviews,
    setup_alarm_subviews,
)
from .dashboard.diagnostics import diagnostics_sections
from .dashboard.monitor import monitor_sections
from .dashboard.primitives import DashboardIndex, load_card_seed
from .measurement_catalog import MeasurementCatalog
from .render_model import RenderModel
from .paths import GeneratorPaths


GENERATED_WARNING = """# GENERATED BY LABPULSE.
# Changes to this file are overwritten by regeneration.
# Edit config.yaml for sensors/grouping or repository dashboard rules for layout.
"""


def dashboard_document(
    config: LabPulseConfig,
    catalog: MeasurementCatalog,
    render_model: RenderModel,
) -> dict[str, object]:
    """Return the complete dashboard document before YAML serialization.

    Monitor and Alarm Setup project logical setups, while Diagnostics projects
    physical services. All views share the canonical catalog and lookup
    index, so repeated presentation never creates a second measurement identity.

    Example output::

        {
            "views": [
                {
                    "title": "Monitor",
                    "path": "monitor",
                    "cards": [
                        {
                            "type": "heading",
                            "heading": "Freezers",
                        },
                    ],
                },
                {
                    "title": "Alarm Setup",
                    "path": "alarm-setup",
                    "cards": [],
                },
            ],
        }
    """

    # Build direct model lookups and load the reusable card rules.
    dashboard_index = DashboardIndex.from_model(render_model, catalog)
    card_rules = load_card_seed()

    # Build the three visible dashboard views in sidebar order.
    visible_views = [
        {
            "title": "Monitor",
            "path": "monitor",
            "cards": monitor_sections(config, catalog, dashboard_index),
        },
        {
            "title": "Alarm Setup",
            "path": ALARM_SETUP_PATH,
            "type": "sections",
            "max_columns": 3,
            "dense_section_placement": False,
            "sections": alarm_setup_landing_sections(render_model, card_rules),
        },
        {
            "title": "Diagnostics",
            "path": "diagnostics",
            "type": "sections",
            "max_columns": 3,
            "dense_section_placement": False,
            "sections": diagnostics_sections(
                catalog, render_model, dashboard_index
            ),
        },
    ]

    # Append hidden setup and power subviews after the visible views.
    return {
        "views": visible_views
        + setup_alarm_subviews(config, catalog, dashboard_index, card_rules)
        + power_alarm_subviews(render_model, card_rules)
    }


def render_yaml_dashboard(
    paths: GeneratorPaths,
    config: LabPulseConfig,
    catalog: MeasurementCatalog,
    render_model: RenderModel,
) -> None:
    """Build and write the generated dashboard to Home Assistant's config.

    The rendering layer returns only plain Python mappings and lists. This
    boundary owns directory creation, deterministic YAML serialization, and
    the generated-file warning; it performs no card-layout decisions.
    """

    # Build the plain dashboard data before serializing it as YAML.
    paths.ha_config_dir.mkdir(parents=True, exist_ok=True)
    dashboard_data = dashboard_document(config, catalog, render_model)

    # Serialize deterministically while preserving human-readable Unicode.
    dashboard_yaml = yaml.safe_dump(
        dashboard_data, sort_keys=False, allow_unicode=True
    )
    # Write the generated warning followed by the complete dashboard YAML.
    paths.dashboard_path.write_text(
        GENERATED_WARNING + dashboard_yaml, encoding="utf-8"
    )
    print(f"Generated {paths.dashboard_path}")


__all__ = ["dashboard_document", "render_yaml_dashboard"]
