"""Generate the three managed Home Assistant files from validated config."""

from __future__ import annotations

import os
from pathlib import Path
import re
import sys
import tempfile

from jinja2 import Environment, FileSystemLoader, StrictUndefined
import yaml

from labpulse.common.config import (
    ConfigDocument,
    ConfigError,
    format_config_error,
    load_config,
)
from labpulse.common.identity import entity_id, slug, stable_id

from .alarm import _yaml_scalar, build_template_context, render_alarm


TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"
UI_FILES = ("automations.yaml", "scripts.yaml", "scenes.yaml")


def _environment() -> Environment:
    """Return the strict Jinja environment shared by dashboard templates."""

    environment = Environment(
        loader=FileSystemLoader(TEMPLATE_DIR),
        undefined=StrictUndefined,
        autoescape=False,
        block_start_string="[%",
        block_end_string="%]",
        variable_start_string="[[",
        variable_end_string="]]",
        trim_blocks=False,
        lstrip_blocks=True,
    )
    environment.filters.update(yaml_scalar=_yaml_scalar, pyrepr=repr)
    environment.globals.update(entity_id=entity_id, stable_id=stable_id, slug=slug)
    return environment


def _render_dashboard(context: dict[str, object]) -> str:
    """Render and validate the final-shaped dashboard template."""

    rendered = _environment().get_template("dashboard.yaml.j2").render(model=context)
    dashboard = _validate_dashboard(rendered)
    return (
        "# GENERATED BY LABPULSE.\n"
        "# Changes to this file are overwritten by regeneration.\n"
        "# Edit config.yaml for sensors/grouping or repository dashboard rules for layout.\n"
        + yaml.safe_dump(dashboard, sort_keys=False, allow_unicode=True)
    )


def _validate_dashboard(rendered: str) -> dict[str, object]:
    """Parse a rendered dashboard and require its public top-level shape."""

    dashboard = yaml.safe_load(rendered)
    if not isinstance(dashboard, dict) or not isinstance(dashboard.get("views"), list):
        raise ValueError("rendered Home Assistant dashboard must contain a views list")
    return dashboard


def _render_configuration() -> str:
    """Render the core config and validate its mapping shape."""

    rendered = _environment().get_template("configuration.yaml.j2").render()
    # PyYAML does not know Home Assistant's include tags. Removing only the tag
    # token leaves ordinary scalar paths and allows the complete mapping to be checked.
    checkable = re.sub(r"!(?:include|include_dir_named)\s+", "", rendered)
    parsed = yaml.safe_load(checkable)
    if not isinstance(parsed, dict):
        raise ValueError("rendered Home Assistant configuration must be a mapping")
    return rendered.rstrip() + "\n"


def _replace_text(path: Path, text: str) -> None:
    """Atomically replace one managed text file on its destination filesystem."""

    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".generating",
        text=True,
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
        os.replace(temporary_name, path)
    except Exception:
        try:
            Path(temporary_name).unlink()
        except FileNotFoundError:
            pass
        raise


def generate_homeassistant(document: ConfigDocument, ha_config_dir: Path) -> None:
    """Render every managed document before atomically installing any of them."""

    ha_config_dir = Path(ha_config_dir).expanduser().resolve()
    context = build_template_context(document.config)
    outputs = {
        ha_config_dir / "configuration.yaml": _render_configuration(),
        ha_config_dir / "packages" / "labpulse_generated.yaml": render_alarm(context),
        ha_config_dir / "labpulse-dashboard.yaml": _render_dashboard(context),
    }

    # Rendering and YAML validation above must finish before live files are touched.
    for path, text in outputs.items():
        _replace_text(path, text)
        print(f"Generated {path}")
    for filename in UI_FILES:
        path = ha_config_dir / filename
        if not path.exists():
            _replace_text(path, "[]\n")
            print(f"Created {path}")


def main(argv: list[str] | None = None) -> int:
    """Load one config file and generate Home Assistant managed output."""

    argv = sys.argv if argv is None else argv
    if len(argv) != 3:
        print(
            "Usage: python3 -m labpulse.homeassistant CONFIG_PATH HA_CONFIG_DIR",
            file=sys.stderr,
        )
        return 2
    try:
        document = load_config(Path(argv[1]).expanduser().resolve())
        generate_homeassistant(document, Path(argv[2]))
    except ConfigError as error:
        print(format_config_error(error), file=sys.stderr)
        return 1
    return 0
