"""Generate the three managed Home Assistant files from validated config."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

from jinja2 import Environment, FileSystemLoader, StrictUndefined
import yaml

from labpulse.common.config import (
    ConfigDocument,
    ConfigError,
    format_config_error,
    load_config,
    render_resolved_config,
    validate_resolved_config,
)
from labpulse.common.identity import entity_id, slug, stable_id
from labpulse.common.generated_files import replace_text

from .alarm import (
    HomeAssistantRenderModel,
    build_template_context,
    render_alarm,
    yaml_scalar,
)


TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"
# Relative paths owned by LabPulse, shared with staged deployment installation.
CONFIGURATION_FILE = Path("configuration.yaml")
ALARM_FILE = Path("packages/labpulse_generated.yaml")
DASHBOARD_FILE = Path("labpulse-dashboard.yaml")
MANAGED_FILES = (CONFIGURATION_FILE, ALARM_FILE, DASHBOARD_FILE)

# Home Assistant expects these files even when the user has not created any UI
# automations, scripts, or scenes. LabPulse creates empty lists but never
# replaces existing user-owned versions.
UI_FILES = ("automations.yaml", "scripts.yaml", "scenes.yaml")


def _environment() -> Environment:
    """Prepare Jinja for LabPulse dashboard templates."""

    # LabPulse and Home Assistant both use Jinja. LabPulse uses square brackets
    # here so Home Assistant's normal ``{{ ... }}`` expressions are left alone.
    environment = Environment(
        loader=FileSystemLoader(TEMPLATE_DIR),
        undefined=StrictUndefined,
        autoescape=False,
        block_start_string="[%",
        block_end_string="%]",
        variable_start_string="[[",
        variable_end_string="]]",
        trim_blocks=False,
        lstrip_blocks=True,
    )
    environment.filters.update(yaml_scalar=yaml_scalar, pyrepr=repr)
    environment.globals.update(entity_id=entity_id, stable_id=stable_id, slug=slug)
    return environment


def _render_dashboard(context: HomeAssistantRenderModel) -> str:
    """Create and check the complete dashboard."""

    # Join every included template before checking the YAML. This catches
    # indentation mistakes where two template files meet.
    rendered = _environment().get_template("dashboard.yaml.j2").render(model=context)
    dashboard = yaml.safe_load(rendered)
    if not isinstance(dashboard, dict) or not isinstance(dashboard.get("views"), list):
        raise ValueError("rendered Home Assistant dashboard must contain a views list")
    return (
        "# GENERATED BY LABPULSE.\n"
        "# Changes to this file are overwritten by regeneration.\n"
        "# Edit config.yaml/config.d for sensors or repository dashboard rules for layout.\n"
        + yaml.safe_dump(dashboard, sort_keys=False, allow_unicode=True)
    )


def _render_configuration() -> str:
    """Create and check the main Home Assistant configuration."""

    rendered = _environment().get_template("configuration.yaml.j2").render()
    # The YAML checker does not understand Home Assistant's ``!include`` words.
    # Remove those words for the check, but keep them in the file we save.
    checkable = re.sub(r"!(?:include|include_dir_named)\s+", "", rendered)
    parsed = yaml.safe_load(checkable)
    if not isinstance(parsed, dict):
        raise ValueError("rendered Home Assistant configuration must be a mapping")
    return rendered.rstrip() + "\n"


def ensure_ui_files(ha_config_dir: Path) -> None:
    """Create missing user-owned files without replacing existing content."""

    for filename in UI_FILES:
        path = ha_config_dir / filename
        if not path.exists():
            replace_text(path, "[]\n")
            print(f"Created {path}")


def generate_homeassistant(document: ConfigDocument, ha_config_dir: Path) -> None:
    """Create and check every LabPulse-owned Home Assistant file."""

    ha_config_dir = Path(ha_config_dir).expanduser().resolve()
    context = build_template_context(document.config)
    # Finish all three files before saving any of them. If one is broken, the
    # existing Home Assistant setup stays unchanged.
    outputs = {
        ha_config_dir / CONFIGURATION_FILE: _render_configuration(),
        ha_config_dir / ALARM_FILE: render_alarm(context),
        ha_config_dir / DASHBOARD_FILE: _render_dashboard(context),
    }

    for path, text in outputs.items():
        replace_text(path, text)
        print(f"Generated {path}")
    ensure_ui_files(ha_config_dir)


def main(argv: list[str] | None = None) -> int:
    """Load one config file and generate Home Assistant managed output."""

    parser = argparse.ArgumentParser(description="Generate Home Assistant files from LabPulse configuration")
    parser.add_argument("config", type=Path, help="Path to LabPulse config YAML")
    parser.add_argument("ha_config_dir", type=Path, help="Home Assistant configuration directory")
    args = parser.parse_args(argv)
    try:
        source_document = load_config(args.config)
        resolved_path = args.config.expanduser().resolve().parent / "config.resolved.yaml"
        resolved_text = render_resolved_config(source_document)
        resolved_document = validate_resolved_config(resolved_text, resolved_path)
        generate_homeassistant(resolved_document, args.ha_config_dir)
        replace_text(resolved_path, resolved_text)
        print(f"Generated {resolved_path}")
    except ConfigError as error:
        print(format_config_error(error), file=sys.stderr)
        return 1
    return 0
