"""Generate the three managed Home Assistant files from validated config."""

from __future__ import annotations

import os
from pathlib import Path
import re
import tempfile

from jinja2 import Environment, FileSystemLoader, StrictUndefined
import yaml

from labpulse.common.config import ConfigDocument
from labpulse.common.identity import entity_id, slug, stable_id

from .alarm import (
    HomeAssistantRenderModel,
    build_template_context,
    render_alarm,
    yaml_scalar,
)


TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"
# Home Assistant expects these files even when the user has not created any UI
# automations, scripts, or scenes. LabPulse creates empty lists but never
# replaces existing user-owned versions.
UI_FILES = ("automations.yaml", "scripts.yaml", "scenes.yaml")


def _environment() -> Environment:
    """Prepare Jinja for LabPulse dashboard templates."""

    # LabPulse and Home Assistant both use Jinja. LabPulse uses square brackets
    # here so Home Assistant's normal ``{{ ... }}`` expressions are left alone.
    environment = Environment(
        loader=FileSystemLoader(TEMPLATE_DIR),
        undefined=StrictUndefined,
        autoescape=False,
        block_start_string="[%",
        block_end_string="%]",
        variable_start_string="[[",
        variable_end_string="]]",
        trim_blocks=False,
        lstrip_blocks=True,
    )
    environment.filters.update(yaml_scalar=yaml_scalar, pyrepr=repr)
    environment.globals.update(entity_id=entity_id, stable_id=stable_id, slug=slug)
    return environment


def _render_dashboard(context: HomeAssistantRenderModel) -> str:
    """Create and check the complete dashboard."""

    # Join every included template before checking the YAML. This catches
    # indentation mistakes where two template files meet.
    rendered = _environment().get_template("dashboard.yaml.j2").render(model=context)
    dashboard = _validate_dashboard(rendered)
    return (
        "# GENERATED BY LABPULSE.\n"
        "# Changes to this file are overwritten by regeneration.\n"
        "# Edit config.yaml for sensors/grouping or repository dashboard rules for layout.\n"
        + yaml.safe_dump(dashboard, sort_keys=False, allow_unicode=True)
    )


def _validate_dashboard(rendered: str) -> dict[str, object]:
    """Check the generated dashboard at the YAML boundary before installation."""

    dashboard = yaml.safe_load(rendered)
    if not isinstance(dashboard, dict) or not isinstance(dashboard.get("views"), list):
        raise ValueError("rendered Home Assistant dashboard must contain a views list")
    return dashboard
def _render_configuration() -> str:
    """Create and check the main Home Assistant configuration."""

    rendered = _environment().get_template("configuration.yaml.j2").render()
    # The YAML checker does not understand Home Assistant's ``!include`` words.
    # Remove those words for the check, but keep them in the file we save.
    checkable = re.sub(r"!(?:include|include_dir_named)\s+", "", rendered)
    parsed = yaml.safe_load(checkable)
    if not isinstance(parsed, dict):
        raise ValueError("rendered Home Assistant configuration must be a mapping")
    return rendered.rstrip() + "\n"


def _replace_text(path: Path, text: str) -> None:
    """Replace one generated file without leaving a half-written file."""

    path.parent.mkdir(parents=True, exist_ok=True)
    # Write beside the final file. The Raspberry Pi can then swap the finished
    # file into place in one step.
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".generating",
        text=True,
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
        # A complete write is made visible in one operation. Home Assistant can
        # never observe half of a generated YAML document.
        os.replace(temporary_name, path)
    except Exception:
        try:
            Path(temporary_name).unlink()
        except FileNotFoundError:
            pass
        raise


def generate_homeassistant(document: ConfigDocument, ha_config_dir: Path) -> None:
    """Create and check every LabPulse-owned Home Assistant file."""

    ha_config_dir = Path(ha_config_dir).expanduser().resolve()
    context = build_template_context(document.config)
    # Finish all three files before saving any of them. If one is broken, the
    # existing Home Assistant setup stays unchanged.
    outputs = {
        ha_config_dir / "configuration.yaml": _render_configuration(),
        ha_config_dir / "packages" / "labpulse_generated.yaml": render_alarm(context),
        ha_config_dir / "labpulse-dashboard.yaml": _render_dashboard(context),
    }

    # Rendering and YAML validation above must finish before live files are touched.
    for path, text in outputs.items():
        _replace_text(path, text)
        print(f"Generated {path}")
    # Users can edit these three files in Home Assistant. Create missing files,
    # but never replace files that are already there.
    for filename in UI_FILES:
        path = ha_config_dir / filename
        if not path.exists():
            _replace_text(path, "[]\n")
            print(f"Created {path}")
