"""Assemble and write the supported LabPulse Lovelace YAML dashboard.

Page-specific cards live in :mod:`labpulse_homeassistant.dashboard`. This
module is the composition and filesystem boundary: it fixes view order,
serializes the resulting plain data, and never accesses Home Assistant's
private ``.storage`` directory.
"""

from __future__ import annotations

import yaml

from labpulse_common.config import LabPulseConfig

from .dashboard.alarm_setup import (
    ALARM_SETUP_PATH,
    alarm_setup_landing_cards,
    power_alarm_subviews,
    setup_alarm_subviews,
)
from .dashboard.diagnostics import diagnostics_cards
from .dashboard.monitor import monitor_sections
from .dashboard.primitives import DashboardIndex, load_card_seed
from .measurement_catalog import MeasurementCatalog
from .render_model import RenderModel
from .paths import GeneratorPaths


GENERATED_WARNING = """# GENERATED BY LABPULSE.
# Changes to this file are overwritten by regeneration.
# Edit config.yaml for sensors/grouping or repository dashboard rules for layout.
"""


def dashboard_document(
    config: LabPulseConfig,
    catalog: MeasurementCatalog,
    model: RenderModel,
) -> dict[str, object]:
    """Return the complete dashboard document before YAML serialization.

    Monitor and Alarm Setup project logical setups, while Diagnostics projects
    physical services. All views share the canonical catalog and lookup
    index, so repeated presentation never creates a second measurement identity.
    """

    index = DashboardIndex.from_model(model)
    seed = load_card_seed()

    # Omitting ``type`` selects Home Assistant's native masonry layout. Each
    # renderer returns self-contained columns so different heights pack cleanly.
    visible_views = [
        {
            "title": "Monitor",
            "path": "monitor",
            "cards": monitor_sections(config, catalog, index),
        },
        {
            "title": "Alarm Setup",
            "path": ALARM_SETUP_PATH,
            "cards": alarm_setup_landing_cards(model, seed),
        },
        {
            "title": "Diagnostics",
            "path": "diagnostics",
            "cards": diagnostics_cards(catalog, model, index),
        },
    ]

    # Subviews follow visible views so Home Assistant keeps them out of the tab
    # bar while their stable navigation paths remain addressable.
    return {
        "views": visible_views
        + setup_alarm_subviews(config, catalog, index, seed)
        + power_alarm_subviews(model, seed)
    }


def render_yaml_dashboard(
    paths: GeneratorPaths,
    config: LabPulseConfig,
    catalog: MeasurementCatalog,
    model: RenderModel,
) -> None:
    """Build and write the generated dashboard to Home Assistant's config.

    The rendering layer returns only plain Python mappings and lists. This
    boundary owns directory creation, deterministic YAML serialization, and
    the generated-file warning; it performs no card-layout decisions.
    """

    paths.ha_config_dir.mkdir(parents=True, exist_ok=True)
    document = dashboard_document(config, catalog, model)
    body = yaml.safe_dump(document, sort_keys=False, allow_unicode=True)
    paths.dashboard_path.write_text(GENERATED_WARNING + body, encoding="utf-8")
    print(f"Generated {paths.dashboard_path}")


__all__ = ["dashboard_document", "render_yaml_dashboard"]
