"""Render the supported LabPulse Lovelace YAML dashboard."""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from labpulse_common.config import LabPulseConfig

from .models import ReadingModel, RenderModel, ServiceModel, SetupAlarmModel
from .paths import GeneratorPaths
from .inventory import InventoryReading, ReadingInventory, ReadingKey
from .template_utils import expand_template


TEMPLATE_DIR = Path(__file__).resolve().parent / "templates" / "dashboard"
GENERATED_WARNING = """# GENERATED BY LABPULSE.
# Changes to this file are overwritten by regeneration.
# Edit config.yaml for sensors/grouping or repository dashboard rules for layout.
"""
DEFAULT_SUBCATEGORY = "Other Readings"


@dataclass(frozen=True)
class DashboardIndex:
    """Resolve canonical inventory items to their Home Assistant render models."""

    services: dict[str, ServiceModel]
    readings: dict[ReadingKey, ReadingModel]
    setups: dict[str, SetupAlarmModel]

    @classmethod
    def from_model(cls, model: RenderModel) -> "DashboardIndex":
        """Build lookup tables without deriving any new physical identities."""

        services = {service.name: service for service in model.services}
        readings = {
            ReadingKey(service.name, reading.name): reading
            for service in model.services
            for reading in service.readings
        }
        setups = {setup.setup_id: setup for setup in model.setups}
        return cls(services=services, readings=readings, setups=setups)


def render_yaml_dashboard(
    paths: GeneratorPaths,
    config: LabPulseConfig,
    inventory: ReadingInventory,
    model: RenderModel,
) -> None:
    """Write the generated YAML-mode dashboard without private-state access."""

    paths.ha_config_dir.mkdir(parents=True, exist_ok=True)
    document = dashboard_document(config, inventory, model)
    body = yaml.safe_dump(document, sort_keys=False, allow_unicode=True)
    paths.dashboard_path.write_text(GENERATED_WARNING + body, encoding="utf-8")
    print(f"Generated {paths.dashboard_path}")


def dashboard_document(
    config: LabPulseConfig,
    inventory: ReadingInventory,
    model: RenderModel,
) -> dict[str, object]:
    """Return one plain Lovelace document with logical and physical projections."""

    index = DashboardIndex.from_model(model)
    seed = load_card_seed()
    return {
        "views": [
            {
                "title": "Monitor",
                "path": "monitor",
                # Omitting a view type uses Home Assistant's native masonry
                # layout. Each generated vertical stack becomes one compact,
                # independently sized column like the original dashboard.
                "cards": monitor_sections(config, inventory, index),
            },
            {
                "title": "Alarm Setup",
                "path": "alarm-setup",
                "type": "sections",
                "sections": alarm_setup_sections(
                    config, inventory, model, index, seed
                ),
            },
            {
                "title": "Diagnostics",
                "path": "diagnostics",
                "type": "sections",
                "sections": diagnostics_sections(inventory, model, index),
            },
        ]
    }


def load_card_seed() -> dict[str, Any]:
    """Load native-card fragments shared with the existing alarm UI."""

    return yaml.safe_load(
        (TEMPLATE_DIR / "cards.yaml").read_text(encoding="utf-8")
    )


def monitor_sections(
    config: LabPulseConfig,
    inventory: ReadingInventory,
    index: DashboardIndex,
) -> list[dict[str, object]]:
    """Render dedicated power and ordered explicit-setup sections."""

    sections: list[dict[str, object]] = []
    setup_labels = {
        setup_id: setup.display_label(setup_id)
        for setup_id, setup in config.setups.items()
    }
    power_service_names = {
        service.name for service in index.services.values() if service.power is not None
    }
    for service in index.services.values():
        if service.power is not None:
            sections.append(power_monitor_section(service))
    for setup_id, items in inventory.by_setup.items():
        setup = config.setups[setup_id]
        ordinary_items = tuple(
            item for item in items if item.key.service_name not in power_service_names
        )
        sections.append(
            monitor_reading_section(
                setup.display_label(setup_id),
                setup.icon,
                ordinary_items,
                index,
                setup_id=setup_id,
                setup_labels=setup_labels,
                show_service_headings=False,
            )
        )
    return sections


def monitor_reading_section(
    title: str,
    icon: str,
    items: tuple[InventoryReading, ...],
    index: DashboardIndex,
    setup_id: str | None,
    setup_labels: dict[str, str],
    show_service_headings: bool,
) -> dict[str, object]:
    """Render one logical section with unlabeled subcategory card boundaries."""

    cards: list[dict[str, object]] = [heading_card(title, icon, "title")]
    if not items:
        cards.append(
            {
                "type": "markdown",
                "content": "No readings are currently assigned to this setup.",
            }
        )
        return {"type": "vertical-stack", "cards": cards}

    service_groups = (
        readings_by_service(items) if show_service_headings else [(None, items)]
    )
    for service_name, service_items in service_groups:
        if service_name is not None:
            cards.append(
                heading_card(index.services[service_name].label, "mdi:chip", "subtitle")
            )
        for _subcategory, grouped_items in readings_by_subcategory(service_items):
            cards.append(readings_card(grouped_items, index, setup_id, setup_labels))
    return {"type": "vertical-stack", "cards": cards}


def readings_by_service(
    items: Iterable[InventoryReading],
) -> list[tuple[str, tuple[InventoryReading, ...]]]:
    """Group readings by physical service in first-seen configuration order."""

    grouped: dict[str, list[InventoryReading]] = {}
    for item in items:
        grouped.setdefault(item.key.service_name, []).append(item)
    return [(name, tuple(readings)) for name, readings in grouped.items()]


def readings_card(
    items: tuple[InventoryReading, ...],
    index: DashboardIndex,
    setup_id: str | None,
    setup_labels: dict[str, str],
) -> dict[str, object]:
    """Return one unlabeled entity box for an internal subcategory."""

    return {
        "type": "entities",
        "show_header_toggle": False,
        "entities": [
            {
                "entity": index.readings[item.key].expected_entity_id,
                "name": monitor_reading_label(item, index, setup_id, setup_labels),
            }
            for item in items
        ],
    }


def power_monitor_section(service: ServiceModel) -> dict[str, object]:
    """Return a dedicated operator-facing UPS summary resembling the original UI."""

    power = service.power
    if power is None:
        raise ValueError("power Monitor section requires a power service")
    return {
        "type": "vertical-stack",
        "cards": [
            heading_card("UPS Power", "mdi:battery-charging", "title"),
            {
                "type": "tile",
                "entity": service.status_entity.entity_id,
                "name": f"{service.label} Status",
            },
            {
                "type": "gauge",
                "entity": power.battery_level.expected_entity_id,
                "name": power.battery_level.label,
                "min": 0,
                "max": 100,
                "severity": {"red": 0, "yellow": 25, "green": 50},
            },
            {
                "type": "entities",
                "show_header_toggle": False,
                "entities": [
                    {"entity": power.state_entity, "name": "Power state"},
                    {
                        "entity": power.mains_present_entity,
                        "name": "External power present",
                    },
                    {
                        "entity": power.voltage.expected_entity_id,
                        "name": power.voltage.label,
                    },
                    {
                        "entity": power.last_outage_started_sensor_entity,
                        "name": "Last outage started",
                    },
                    {
                        "entity": power.last_outage_duration_sensor_entity,
                        "name": "Last outage duration",
                    },
                ],
            },
        ],
    }


def readings_by_subcategory(
    items: Iterable[InventoryReading],
) -> list[tuple[str, tuple[InventoryReading, ...]]]:
    """Group canonical readings by optional subcategory in first-seen order."""

    grouped: dict[str, list[InventoryReading]] = {}
    for item in items:
        grouped.setdefault(item.reading.subcategory or DEFAULT_SUBCATEGORY, []).append(
            item
        )
    return [(name, tuple(readings)) for name, readings in grouped.items()]


def monitor_reading_label(
    item: InventoryReading,
    index: DashboardIndex,
    setup_id: str | None,
    setup_labels: dict[str, str],
) -> str:
    """Return one contextual label without changing the referenced entity."""

    label = index.readings[item.key].label
    scope = item.reading.setups
    if scope is not None and len(item.effective_setup_ids) > 1:
        other_ids = tuple(
            candidate for candidate in item.effective_setup_ids if candidate != setup_id
        )
        other_labels = tuple(setup_labels[candidate] for candidate in other_ids)
        return f"{label} (Shared with {', '.join(other_labels)})"
    return label


def alarm_setup_sections(
    config: LabPulseConfig,
    inventory: ReadingInventory,
    model: RenderModel,
    index: DashboardIndex,
    seed: dict[str, Any],
) -> list[dict[str, object]]:
    """Render setup-grouped alarm controls with per-reading timing."""

    sections = [notification_controls_section(model, seed)]
    bulk = bulk_timing_section(model, seed)
    if bulk is not None:
        sections.append(bulk)

    for setup_id, items in inventory.by_setup.items():
        selected = ordinary_alarm_readings(
            items,
            index,
        )
        if not selected:
            continue
        sections.append(
            alarm_reading_section(
                config.setups[setup_id].display_label(setup_id),
                config.setups[setup_id].icon,
                selected,
                index,
                seed,
                index.setups[setup_id],
            )
        )

    power = power_alarm_section(model, seed)
    if power is not None:
        sections.append(power)
    return sections


def notification_controls_section(
    model: RenderModel, seed: dict[str, Any]
) -> dict[str, object]:
    """Render the existing global notification controls."""

    rules = seed["global_alarm_setup"]
    context = {"model": model}
    return {
        "type": "grid",
        "cards": [
            expand_template(rules["heading_card"], context),
            expand_template(rules["settings_card"], context),
            expand_template(rules["phone_book_button"], context),
        ],
    }


def bulk_timing_section(
    model: RenderModel, seed: dict[str, Any]
) -> dict[str, object] | None:
    """Render setup-targeted bulk timing inputs with explicit confirmation."""

    if not model.bulk_timing_targets:
        return None
    rules = seed["bulk_timing"]
    context = {"model": model}
    return {
        "type": "grid",
        "cards": [
            expand_template(rules["heading_card"], context),
            expand_template(rules["settings_card"], context),
            expand_template(rules["apply_button"], context),
        ],
    }


def ordinary_alarm_readings(
    items: Iterable[InventoryReading], index: DashboardIndex
) -> tuple[InventoryReading, ...]:
    """Exclude dedicated power readings governed by power lifecycle controls."""

    return tuple(
        item for item in items if index.services[item.key.service_name].power is None
    )


def alarm_reading_section(
    title: str,
    icon: str,
    items: tuple[InventoryReading, ...],
    index: DashboardIndex,
    seed: dict[str, Any],
    setup: SetupAlarmModel,
) -> dict[str, object]:
    """Render one classification of canonical per-reading alarm controls."""

    return {
        "type": "grid",
        "cards": [heading_card(title, icon, "title")]
        + setup_mute_cards(setup, seed)
        + alarm_control_cards(items, index, seed),
    }


def setup_mute_cards(
    setup: SetupAlarmModel, seed: dict[str, Any]
) -> list[dict[str, object]]:
    """Render a direct toggle or a confirmed shared-reading mute transition."""

    rules = seed["alarm_setup_sections"]
    context = {"setup": setup}
    if not setup.shared_reading_labels:
        return [expand_template(rules["setup_mute_tile"], context)]
    return [
        expand_template(rules["shared_setup_mute_off"], context),
        expand_template(rules["shared_setup_mute_on"], context),
    ]


def alarm_control_cards(
    items: Iterable[InventoryReading],
    index: DashboardIndex,
    seed: dict[str, Any],
) -> list[dict[str, object]]:
    """Render one expansion toggle and conditional settings card per reading."""

    cards: list[dict[str, object]] = []
    rules = seed["alarm_setup_sections"]
    for item in items:
        context = {
            "service": index.services[item.key.service_name],
            "reading": index.readings[item.key],
        }
        cards.append(expand_template(rules["controls_toggle_tile"], context))
        cards.append(expand_template(rules["reading_settings_card"], context))
    return cards


def power_alarm_section(
    model: RenderModel, seed: dict[str, Any]
) -> dict[str, object] | None:
    """Render each dedicated power lifecycle control card exactly once."""

    cards = [heading_card("Power Monitoring", "mdi:battery-charging", "title")]
    rules = seed["power_alarm_setup"]
    for service in model.services:
        if service.power is None:
            continue
        cards.append(heading_card(service.label, "mdi:chip", "subtitle"))
        cards.append(
            expand_template(
                rules["settings_card"],
                {"service": service, "power": service.power},
            )
        )
    return {"type": "grid", "cards": cards} if len(cards) > 1 else None


def diagnostics_sections(
    inventory: ReadingInventory,
    model: RenderModel,
    index: DashboardIndex,
) -> list[dict[str, object]]:
    """Render every physical reading once under its owning service."""

    sections: list[dict[str, object]] = []
    for service in model.services:
        items = inventory.by_service[service.name]
        cards: list[dict[str, object]] = [
            heading_card(service.label, "mdi:chip", "title"),
            {"type": "tile", "entity": service.status_entity_id, "name": "Service status"},
            {
                "type": "entities",
                "title": "Service Health",
                "show_header_toggle": False,
                "entities": [
                    {"entity": service.health_unhealthy_entity, "name": "Service unhealthy"},
                    {"entity": service.health_fault_active_entity, "name": "Fault active"},
                ],
            },
            {
                "type": "entities",
                "title": "Physical Readings",
                "show_header_toggle": False,
                "entities": [
                    {
                        "entity": index.readings[item.key].expected_entity_id,
                        "name": index.readings[item.key].label,
                    }
                    for item in items
                ],
            },
        ]
        if service.power is not None:
            cards.append(power_diagnostics_card(service))
        else:
            cards.append(alarm_diagnostics_card(service))
        sections.append({"type": "grid", "cards": cards})
    return sections


def power_diagnostics_card(service: ServiceModel) -> dict[str, object]:
    """Return derived power lifecycle diagnostics without repeating raw readings."""

    power = service.power
    if power is None:
        raise ValueError("power diagnostics require a power service")
    return {
        "type": "entities",
        "title": "Power Lifecycle",
        "show_header_toggle": False,
        "entities": [
            {"entity": power.state_entity, "name": "Power state"},
            {"entity": power.mains_present_entity, "name": "External power present"},
            {"entity": power.sensor_fault_entity, "name": "Power sensor fault"},
            {"entity": power.outage_active_entity, "name": "Outage active"},
            {"entity": power.last_outage_started_sensor_entity, "name": "Last outage started"},
            {"entity": power.last_outage_duration_sensor_entity, "name": "Last outage duration"},
        ],
    }


def alarm_diagnostics_card(service: ServiceModel) -> dict[str, object]:
    """Return existing per-reading alarm states and raw diagnostic zones."""

    entities: list[dict[str, str]] = []
    for reading in service.readings:
        entities.extend(
            [
                {
                    "entity": reading.alarm_state_entity,
                    "name": f"{reading.label} alarm state",
                },
                {
                    "entity": reading.danger_zone_entity,
                    "name": f"{reading.label} danger zone",
                },
                {
                    "entity": reading.recovery_zone_entity,
                    "name": f"{reading.label} recovery zone",
                },
                {
                    "entity": reading.sensor_fault_zone_entity,
                    "name": f"{reading.label} sensor fault",
                },
            ]
        )
    return {
        "type": "entities",
        "title": "Alarm Diagnostics",
        "show_header_toggle": False,
        "entities": entities,
    }


def heading_card(title: str, icon: str, style: str) -> dict[str, object]:
    """Return one native Home Assistant heading card."""

    return {
        "type": "heading",
        "heading": title,
        "heading_style": style,
        "icon": icon,
    }
